### ISSUE TITLE
ui-v-tab使用反馈

### ISSUE THREAD

**Issue by a596544022** [uileader/touchui#22]
```
<ui-v-tab wx:for="{{ tabItems }}">
    {{ item.name }}
</ui-v-tab>
```
里面的tabItems 默认为空数组，然后通过setData来设置的话，会报错
```
thirdScriptError
Cannot read property 'setData' of undefined; [Component] Lifetime Method Error @ packages/touchui-wx-components/ui-v-tabs/dist/index#ready
TypeError: Cannot read property 'setData' of undefined
    at r._initChildActive (http://127.0.0.1:39865/appservice/packages/touchui-wx-components/ui-v-tabs/dist/index.js:87:46)
    at r._init (http://127.0.0.1:39865/appservice/packages/touchui-wx-components/ui-v-tabs/dist/index.js:75:12)
    at ready (http://127.0.0.1:39865/appservice/packages/touchui-wx-components/ui-v-tabs/dist/index.js:68:10)
    at r.safeCallback (http://127.0.0.1:39865/appservice/__dev__/WAService.js:14:1544)
    at r.call (http://127.0.0.1:39865/appservice/__dev__/WAService.js:14:1308)
    at i.p.triggerLifeTime (http://127.0.0.1:39865/appservice/__dev__/WAService.js:15:7042)
    at http://127.0.0.1:39865/appservice/__dev__/WAService.js:16:8418
    at d (http://127.0.0.1:39865/appservice/__dev__/WAService.js:16:10639)
    at a (http://127.0.0.1:39865/appservice/appservice?t=1529139472121:1120:9472)
    at e.registerCallback (http://127.0.0.1:39865/appservice/appservice?t=1529139472121:1120:9659)
```
通过断点发现是因为没有找到节点，具体怎么解决尚不清楚

**Comment by uileader** [comment]
含有子组件的动态渲染需要有个判断。见文档：
http://www.touchui.io/touchui_doc_wx/component/summary/Introduction
